// Kilnry — https://github.com/ApoorvDixitt/kilnry
// Copyright (c) 2026 Apoorv Dixit. Licensed under the Sustainable Use License 1.0.
// SPDX-License-Identifier: LicenseRef-Sustainable-Use-1.0
// See LICENSE.md in the repository root. You may not remove or obscure this notice.

// Generated by `pnpm gen:versions` (scripts/versions.ts) from the installed
// workspace dependencies; do not edit. scripts/versions.test.ts fails when this
// file and the install disagree (F-61).

export const BUILD_PINS = { next: '16.3.6', pglite: '0.5.8' } as const;
