// Kilnry — https://github.com/ApoorvDixitt/kilnry
// Copyright (c) 2026 Apoorv Dixit. Licensed under the Sustainable Use License 1.0.
// SPDX-License-Identifier: LicenseRef-Sustainable-Use-1.0
// See LICENSE.md in the repository root. You may not remove or obscure this notice.

// The commit after which decision D-50's readable-subject rule applies. Every
// commit up to and including the M2 completion commit is exempt so the older
// history, written before this rule existed, does not fail the check.
export const SUBJECT_RULE_BASE = '75edae573d2b4828dfd771bbf036fef01e2e94f3';

const SUBJECT_FORMAT = /^(feat|fix|test|docs|refactor|perf|chore)\([a-z-]+\): .+/;
const FEATURE_ID = /\(F-[A-Z]{3}-\d{2}\)$/;
const RELEASE_EXEMPT = /^chore\(release\): v\d+\.\d+\.\d+$/;
const TRAILER = /^(Co-authored-by|Signed-off-by|Generated-by|Generated-with|Co-developed-by):/im;

// Words that make a public history unreadable. "complete m3", "finish" and the
// rest hide what actually changed, so decision D-50 forbids them in subjects.
const BANNED_WORDS = ['wip', 'misc', 'updates', 'cleanup', 'stabilize', 'tweaks', 'finish', 'various'];
const BANNED_MILESTONE = /\bcomplete m\d+\b/i;

const MAX_SUBJECT_LENGTH = 100;

export interface SubjectCheckInput {
  // The full commit message: first line is the subject, the rest is the body.
  message: string;
  // True when the commit changes files under apps/ or packages/, which is where
  // a feat or fix must carry a feature identifier such as (F-CRE-06).
  touchesProductCode: boolean;
}

// Returns a human-readable reason the subject is rejected, or null when the
// message satisfies every rule in decision D-50.
export function checkCommitSubject({ message, touchesProductCode }: SubjectCheckInput): string | null {
  const normalised = message.replace(/^\uFEFF/, '');
  const lines = normalised.split('\n');
  const subject = (lines[0] ?? '').trim();
  const body = lines.slice(1).join('\n');

  // A merge commit is generated by git itself, not authored by a person, so it
  // is left alone rather than forced into the Conventional Commits shape.
  if (/^Merge /.test(subject)) return null;

  if (RELEASE_EXEMPT.test(subject)) {
    if (TRAILER.test(body))
      return 'the message must not contain a Co-authored-by, Signed-off-by or similar trailer';
    return null;
  }

  if (!SUBJECT_FORMAT.test(subject)) {
    return `the subject must read like "type(area): what changed and why it matters", but was "${subject}"`;
  }

  if (subject.length > MAX_SUBJECT_LENGTH) {
    return `the subject must be at most ${MAX_SUBJECT_LENGTH} characters, but was ${subject.length}`;
  }

  const lowerSubject = subject.toLowerCase();
  for (const word of BANNED_WORDS) {
    if (new RegExp(`\\b${word}\\b`).test(lowerSubject)) {
      return `the subject must not use the vague word "${word}"; describe what actually changed`;
    }
  }
  if (BANNED_MILESTONE.test(subject)) {
    return 'the subject must not say "complete M<n>"; describe the specific change instead';
  }

  const type = subject.slice(0, subject.indexOf('('));
  if ((type === 'feat' || type === 'fix') && touchesProductCode && !FEATURE_ID.test(subject)) {
    return 'a feat or fix that changes apps/ or packages/ must end with a feature identifier such as (F-CRE-06)';
  }

  if (TRAILER.test(body)) {
    return 'the message must not contain a Co-authored-by, Signed-off-by or similar trailer';
  }

  return null;
}
