// Kilnry — https://github.com/ApoorvDixitt/kilnry
// Copyright (c) 2026 Apoorv Dixit. Licensed under the Sustainable Use License 1.0.
// SPDX-License-Identifier: LicenseRef-Sustainable-Use-1.0
// See LICENSE.md in the repository root. You may not remove or obscure this notice.

// The build-time versions Settings › About prints (PRD-16 §11: "versions from
// TRD-02 pins at build time, runtime values at run time"). @kilnry/core cannot
// require `next` or `@electric-sql/pglite` at run time — neither is its
// dependency, and pglite does not export its package.json — so the About line
// read "Next unknown · PGlite unknown" (F-61). The versions are read here from
// the packages the frozen install placed for the workspaces that depend on
// them, which are the lockfile's resolutions, and written into core's source.

import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';

export const GENERATED_PATH = 'packages/core/src/about/versions.generated.ts';

// Walk up from a package's resolved entry to its own package.json, for a
// package whose `exports` does not list `./package.json`.
function installedVersion(fromWorkspace: string, name: string, root: string): string {
  const require = createRequire(resolve(root, fromWorkspace, 'package.json'));
  let dir = dirname(require.resolve(name));
  for (;;) {
    try {
      const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as {
        name?: string;
        version?: string;
      };
      if (pkg.name === name && typeof pkg.version === 'string') return pkg.version;
    } catch {
      // No package.json at this level; keep walking up.
    }
    const parent = dirname(dir);
    if (parent === dir) throw new Error(`No package.json for ${name} above ${require.resolve(name)}.`);
    dir = parent;
  }
}

export function buildPins(root = process.cwd()): { next: string; pglite: string } {
  return {
    next: installedVersion('apps/web', 'next', root),
    pglite: installedVersion('packages/db', '@electric-sql/pglite', root),
  };
}

export function renderGenerated(pins: { next: string; pglite: string }): string {
  return `// Kilnry — https://github.com/ApoorvDixitt/kilnry
// Copyright (c) 2026 Apoorv Dixit. Licensed under the Sustainable Use License 1.0.
// SPDX-License-Identifier: LicenseRef-Sustainable-Use-1.0
// See LICENSE.md in the repository root. You may not remove or obscure this notice.

// Generated by \`pnpm gen:versions\` (scripts/versions.ts) from the installed
// workspace dependencies; do not edit. scripts/versions.test.ts fails when this
// file and the install disagree (F-61).

export const BUILD_PINS = { next: '${pins.next}', pglite: '${pins.pglite}' } as const;
`;
}
