// Kilnry — https://github.com/ApoorvDixitt/kilnry
// Copyright (c) 2026 Apoorv Dixit. Licensed under the Sustainable Use License 1.0.
// SPDX-License-Identifier: LicenseRef-Sustainable-Use-1.0
// See LICENSE.md in the repository root. You may not remove or obscure this notice.

import type { ModelManifest } from '../manifest.js';
import { referenceRoles, seed, videoSupports } from './helpers.js';

export const goldenSupportSeed: ModelManifest[] = [
  seed({
    provider: 'google',
    model_id: 'veo-3.1-generate-preview',
    display_name: 'Veo 3.1',
    capabilities: ['text2video', 'image2video'],
    price_rule: {
      kind: 'per_second_tiered',
      tiers: {
        '720p': { no_audio: 0.4, audio: 0.4 },
        '1080p': { no_audio: 0.4, audio: 0.4 },
        '4k': { no_audio: 0.4, audio: 0.6 },
      },
    },
    quality_tier: 'premium',
    supports: videoSupports({
      resolutions: ['720p', '1080p', '4k'],
      durations: [4, 6, 8],
      audio: true,
      seed: true,
    }),
    retention_days: 2,
    moderation: { http: 200, shape: 'raiMediaFilteredCount', billed: 'no' },
    source_url: 'https://ai.google.dev/gemini-api/docs/veo',
  }),
  seed({
    provider: 'google',
    model_id: 'veo-3.1-fast-generate-preview',
    display_name: 'Veo 3.1 Fast',
    capabilities: ['text2video', 'image2video'],
    price_rule: {
      kind: 'per_second_tiered',
      tiers: {
        '720p': { no_audio: 0.1, audio: 0.1 },
        '1080p': { no_audio: 0.12, audio: 0.12 },
        '4k': { no_audio: 0.3, audio: 0.3 },
      },
    },
    supports: videoSupports({
      resolutions: ['720p', '1080p', '4k'],
      durations: [4, 6, 8],
      audio: true,
      seed: true,
    }),
    retention_days: 2,
    moderation: { http: 200, shape: 'raiMediaFilteredCount', billed: 'no' },
    source_url: 'https://ai.google.dev/gemini-api/docs/veo',
  }),
  seed({
    provider: 'google',
    model_id: 'gemini-3.1-flash-image',
    display_name: 'Gemini 3.1 Flash Image',
    capabilities: ['text2image', 'image_edit'],
    price_rule: {
      kind: 'output_tokens_table',
      tokens_by_size: { '0.5K': 747, '1K': 1120, '2K': 1680, '4K': 2520 },
      usd_per_token: 0.00006,
      input_usd_per_token: 0.0000005,
      input_tokens_per_image: 560,
    },
    supports: { resolutions: ['0.5K', '1K', '2K', '4K'], references_max: 14, aspect_ratios: ['auto'] },
    media_roles: referenceRoles(14),
    retention_days: null,
    moderation: { http: 200, shape: 'promptFeedback.blockReason', billed: 'no' },
    source_url: 'https://ai.google.dev/gemini-api/docs/pricing',
  }),
  seed({
    provider: 'google',
    model_id: 'gemini-3-pro-image',
    display_name: 'Gemini 3 Pro Image',
    capabilities: ['text2image', 'image_edit'],
    price_rule: {
      kind: 'output_tokens_table',
      tokens_by_size: { '1K': 1120, '2K': 1120, '4K': 2000 },
      usd_per_token: 0.00012,
      input_usd_per_token: 0.000002,
      input_tokens_per_image: 560,
    },
    quality_tier: 'premium',
    supports: { resolutions: ['1K', '2K', '4K'], references_max: 14, aspect_ratios: ['auto'] },
    media_roles: referenceRoles(14),
    retention_days: null,
    moderation: { http: 200, shape: 'promptFeedback.blockReason', billed: 'no' },
    source_url: 'https://ai.google.dev/gemini-api/docs/pricing',
  }),
  seed({
    provider: 'openai',
    model_id: 'gpt-image-2',
    display_name: 'GPT Image 2',
    capabilities: ['text2image', 'image_edit'],
    price_rule: {
      kind: 'image_tokens',
      table: {
        low: { '1024x1024': 0.006, '1024x1536': 0.005, '1536x1024': 0.005 },
        medium: { '1024x1024': 0.053, '1024x1536': 0.041, '1536x1024': 0.041 },
        high: { '1024x1024': 0.211, '1024x1536': 0.165, '1536x1024': 0.165 },
      },
      rates: { image_out: 0.00003, image_in: 0.000008, text_in: 0.000005 },
      input_tokens_per_ref: 3050,
    },
    quality_tier: 'premium',
    supports: { resolutions: ['1K', '2K', '4K'], references_max: 16, aspect_ratios: ['auto'] },
    media_roles: referenceRoles(16),
    retention_days: null,
    moderation: { http: 400, shape: 'moderation_blocked', billed: 'no' },
    source_url: 'https://developers.openai.com/api/docs/pricing',
  }),
  seed({
    provider: 'minimax',
    model_id: 'MiniMax-H3',
    display_name: 'MiniMax H3',
    capabilities: ['text2video', 'image2video', 'reference2video'],
    price_rule: {
      kind: 'per_second_tiered',
      tiers: { '768P': { no_audio: 0.08, audio: 0.08 }, '2K': { no_audio: 0.13, audio: 0.13 } },
      ref_image_free: 5,
      ref_image_usd: 0.04,
    },
    supports: videoSupports({
      resolutions: ['768P', '2K'],
      durations: { min: 4, max: 15, step: 1 },
      audio: true,
      references: 12,
    }),
    media_roles: referenceRoles(12),
    retention_days: 0,
    moderation: { http: 422, shape: '1026', billed: 'no' },
    source_url: 'https://platform.minimax.io/docs/guides/pricing-paygo',
  }),
  seed({
    provider: 'elevenlabs',
    model_id: 'eleven_v3',
    display_name: 'Eleven v3',
    capabilities: ['tts'],
    price_rule: { kind: 'per_1k_chars', amount: 0.1 },
    quality_tier: 'premium',
    supports: { resolutions: [], references_max: 0, voice_ids: true, aspect_ratios: ['auto'] },
    retention_days: null,
    moderation: { http: 422, shape: 'detail.status', billed: 'no' },
    source_url: 'https://elevenlabs.io/pricing/api',
  }),
  seed({
    provider: 'elevenlabs',
    model_id: 'eleven_flash_v2_5',
    display_name: 'Eleven Flash v2.5',
    capabilities: ['tts'],
    price_rule: { kind: 'per_1k_chars', amount: 0.05 },
    supports: { resolutions: [], references_max: 0, voice_ids: true, aspect_ratios: ['auto'] },
    retention_days: null,
    moderation: { http: 422, shape: 'detail.status', billed: 'no' },
    source_url: 'https://elevenlabs.io/pricing/api',
  }),
  seed({
    provider: 'elevenlabs',
    model_id: 'scribe_v2',
    display_name: 'Scribe v2',
    capabilities: ['stt'],
    price_rule: { kind: 'per_minute', amount: 0.003667, unit_of: 'input', per_target_language: false },
    quality_tier: 'premium',
    supports: { resolutions: [], references_max: 0, aspect_ratios: ['auto'] },
    media_roles: [{ role: 'audio', min: 1, max: 1, kinds: ['audio'] }],
    retention_days: null,
    moderation: { http: 422, shape: 'detail.status', billed: 'no' },
    source_url: 'https://elevenlabs.io/pricing/api',
  }),
  seed({
    provider: 'minimax',
    model_id: 'speech-2.8-turbo',
    display_name: 'MiniMax Speech Turbo',
    capabilities: ['tts'],
    price_rule: { kind: 'per_1k_chars', amount: 0.06 },
    quality_tier: 'draft',
    supports: { resolutions: [], references_max: 0, voice_ids: true, aspect_ratios: ['auto'] },
    retention_days: null,
    moderation: { http: 422, shape: '1026', billed: 'no' },
    source_url: 'https://platform.minimax.io/docs/guides/pricing-paygo',
  }),
  seed({
    provider: 'higgsfield',
    model_id: 'kling-video/v3.0/std/image-to-video',
    display_name: 'Kling 3.0 Standard via Higgsfield',
    capabilities: ['image2video'],
    price_rule: {
      kind: 'provider_estimate',
      endpoint: 'higgsfield_estimate',
      fallback: { kind: 'per_second_tiered', tiers: { '720p': { no_audio: 0.084 } } },
    },
    supports: videoSupports({
      resolutions: ['720p'],
      durations: { min: 3, max: 15, step: 1 },
      startEnd: true,
    }),
    retention_days: 7,
    moderation: { http: null, shape: 'nsfw', billed: 'no' },
    training_on_inputs: true,
    source_url: 'https://docs.higgsfield.ai/docs/llms.txt',
  }),
];
